/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JFrame;

/**
 *
 * @author Prerna
 */
public class Register extends javax.swing.JFrame {
    private InternalFrame JInternalFrame;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCA = new javax.swing.JLabel();
        jCC = new javax.swing.JButton();
        jCR = new javax.swing.JButton();
        jAS = new javax.swing.JButton();
        jNS = new javax.swing.JButton();
        jSA = new javax.swing.JButton();
        jSegments = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Campaign Management");

        jCA.setFont(new java.awt.Font("Gisha", 1, 24)); // NOI18N
        jCA.setForeground(new java.awt.Color(102, 0, 102));
        jCA.setText("COMMON ACTIONS");

        jCC.setBackground(new java.awt.Color(204, 204, 204));
        jCC.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        jCC.setForeground(new java.awt.Color(0, 51, 255));
        jCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images.jpg"))); // NOI18N
        jCC.setText("Create Campaign");
        jCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCActionPerformed(evt);
            }
        });

        jCR.setBackground(new java.awt.Color(204, 204, 204));
        jCR.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        jCR.setForeground(new java.awt.Color(0, 51, 255));
        jCR.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prerna\\Documents\\NetBeansProjects\\bepro\\gui\\src\\gui\\images (1).jpg")); // NOI18N
        jCR.setText("Campaign Reports");
        jCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCRActionPerformed(evt);
            }
        });

        jAS.setBackground(new java.awt.Color(204, 204, 204));
        jAS.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        jAS.setForeground(new java.awt.Color(0, 51, 255));
        jAS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prerna\\Documents\\NetBeansProjects\\bepro\\gui\\src\\gui\\images (3).jpg")); // NOI18N
        jAS.setText("Add Subscriber");
        jAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jASActionPerformed(evt);
            }
        });

        jNS.setBackground(new java.awt.Color(204, 204, 204));
        jNS.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        jNS.setForeground(new java.awt.Color(0, 51, 255));
        jNS.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prerna\\Documents\\NetBeansProjects\\bepro\\gui\\src\\gui\\images (7).jpg")); // NOI18N
        jNS.setText("New Subscriber");
        jNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNSActionPerformed(evt);
            }
        });

        jSA.setBackground(new java.awt.Color(204, 204, 204));
        jSA.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        jSA.setForeground(new java.awt.Color(0, 51, 255));
        jSA.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prerna\\Documents\\NetBeansProjects\\bepro\\gui\\src\\gui\\images (4).jpg")); // NOI18N
        jSA.setText("Subscriber Actions");
        jSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSAActionPerformed(evt);
            }
        });

        jSegments.setBackground(new java.awt.Color(204, 204, 204));
        jSegments.setFont(new java.awt.Font("Lucida Console", 1, 13)); // NOI18N
        jSegments.setForeground(new java.awt.Color(0, 51, 255));
        jSegments.setIcon(new javax.swing.ImageIcon("C:\\Users\\Prerna\\Documents\\NetBeansProjects\\bepro\\gui\\src\\gui\\images (6).jpg")); // NOI18N
        jSegments.setText("Segments");
        jSegments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSegmentsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("RECIPIENT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("OPENS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("REPLIES");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("CLICKS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("UNSUBSCRIBE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSegments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCA)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(22, 22, 22))
                            .addComponent(jCR))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(jCC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jAS)
                        .addComponent(jNS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSA)
                        .addComponent(jSegments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNSActionPerformed
InternalFrame f =new InternalFrame();
f.setVisible(true);
    }//GEN-LAST:event_jNSActionPerformed

    private void jCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCActionPerformed
JFrame one = new one();
    one.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jCCActionPerformed

    private void jCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCRActionPerformed
    JFrame one = new one();
    one.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jCRActionPerformed

    private void jASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jASActionPerformed
JFrame one = new one();
    one.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jASActionPerformed

    private void jSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSAActionPerformed
JFrame one = new one();
    one.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jSAActionPerformed

    private void jSegmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSegmentsActionPerformed
JFrame one = new one();
    one.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jSegmentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAS;
    private javax.swing.JLabel jCA;
    private javax.swing.JButton jCC;
    private javax.swing.JButton jCR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jNS;
    private javax.swing.JButton jSA;
    private javax.swing.JButton jSegments;
    // End of variables declaration//GEN-END:variables
}
